<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE aeropuerto [

<!ELEMENT aeropuerto (nombre,vuelos,fecha) >

<!ELEMENT nombre (#PCDATA) >
<!ELEMENT fecha (#PCDATA) >

<!ELEMENT vuelos (vuelo+) >

<!ELEMENT vuelo (diario?,origen,destino,hora_salida,hora_llegada) >
<!ATTLIST vuelo codigo ID #REQUIRED >
<!ATTLIST vuelo estado (C|R|E) "E" >

<!ELEMENT diario EMPTY >
<!ELEMENT origen (#PCDATA) >
<!ELEMENT destino (#PCDATA) >
<!ELEMENT hora_salida (#PCDATA) >
<!ELEMENT hora_llegada (#PCDATA) >

]>


<aeropuerto>
<nombre>AGP</nombre>
    <vuelos>
        <vuelo codigo="V22" estado="R">
            <diario/>
            <origen>New York</origen>
            <destino>Chicago</destino>
            <hora_salida>9:30</hora_salida>
            <hora_llegada>11:30</hora_llegada>
        </vuelo>
        <vuelo codigo="V23" estado="C">
            <diario/>
            <origen>New York</origen>
            <destino>Miami</destino>
            <hora_salida>10:15</hora_salida>
            <hora_llegada>11:15</hora_llegada>
        </vuelo>
    </vuelos>
    <fecha>12/01/2023</fecha>
</aeropuerto>

