<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE mame[
<!ELEMENT mame (arcade)+>
<!ELEMENT arcade (name,description,year,manufacturer,is_runnable,driver_status,display_type,display_orientation,sourcefile)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT manufacturer (#PCDATA)>
<!ELEMENT is_runnable (#PCDATA)>
<!ELEMENT driver_status (#PCDATA)>
<!ELEMENT display_type (#PCDATA)>
<!ELEMENT display_orientation (#PCDATA)>
<!ELEMENT sourcefile (#PCDATA)>
]>

<mame>
  <arcade>
    <name>mag_day</name>
    <description>A Day In Space (31/03/87)</description>
    <year>1987</year>
    <manufacturer>EFO SA / Cedar</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>INCOMPLETO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>VERTICAL</display_orientation>
    <sourcefile>cedar_magnet.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>cedmag</name>
    <description>Magnet System</description>
    <year>1987</year>
    <manufacturer>EFO SA / Cedar</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>cedar_magnet.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>ad2083</name>
    <description>A. D. 2083</description>
    <year>1983</year>
    <manufacturer>Midcoin</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>INCOMPLETO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>VERTICAL</display_orientation>
    <sourcefile>scramble.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>abcop</name>
    <description>A.B. Cop (World) (FD1094 317-0169b)</description>
    <year>1990</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>segaxbd.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>ar_argh</name>
    <description>Aaargh (Arcadia)</description>
    <year>1988</year>
    <manufacturer>Arcadia Systems</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>arsystems.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>ar_bios</name>
    <description>Arcadia System BIOS</description>
    <year>1988</year>
    <manufacturer>Arcadia Systems</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>arsystems.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>ace</name>
    <description>Ace</description>
    <year>1976</year>
    <manufacturer>Allied Leisure</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>ace.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>aceattac</name>
    <description>Ace Attacker (FD1094 317-0059)</description>
    <year>1988</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>VERTICAL</display_orientation>
    <sourcefile>segas16b.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>acedrvrw</name>
    <description>Ace Driver: Racing Evolution (Rev. AD2, World)</description>
    <year>1994</year>
    <manufacturer>Namco</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>INCOMPLETO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>namcos22.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>namcoc74</name>
    <description>Namco C74 (M37702)</description>
    <year>-</year>
    <manufacturer>-</manufacturer>
    <is_runnable>NO</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>-</display_type>
    <display_orientation>-</display_orientation>
    <sourcefile>src/mame/machine/namcomcu.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>victlapw</name>
    <description>Ace Driver: Victory Lap (Rev. ADV2, World)</description>
    <year>1996</year>
    <manufacturer>Namco</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>INCOMPLETO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>namcos22.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>acrobatm</name>
    <description>Acrobat Mission</description>
    <year>1991</year>
    <manufacturer>UPL (Taito license)</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>VERTICAL</display_orientation>
    <sourcefile>nmk16.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>nmk004</name>
    <description>NMK004</description>
    <year>-</year>
    <manufacturer>-</manufacturer>
    <is_runnable>NO</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>-</display_type>
    <display_orientation>-</display_orientation>
    <sourcefile>src/mame/machine/nmk004.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>dogfgt</name>
    <description>Acrobatic Dog-Fight</description>
    <year>1984</year>
    <manufacturer>Technos Japan</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>dogfgt.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>nss_actr</name>
    <description>Act Raiser (Nintendo Super System)</description>
    <year>1992</year>
    <manufacturer>Enix</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>nss.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>nss</name>
    <description>Nintendo Super System BIOS</description>
    <year>199?</year>
    <manufacturer>Nintendo</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>nss.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>s_smp</name>
    <description>Nintendo/Sony S-SMP</description>
    <year>-</year>
    <manufacturer>-</manufacturer>
    <is_runnable>NO</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>-</display_type>
    <display_orientation>-</display_orientation>
    <sourcefile>src/devices/machine/s_smp.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>m50458</name>
    <description>Mitsubishi M50458 OSD</description>
    <year>-</year>
    <manufacturer>-</manufacturer>
    <is_runnable>NO</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>-</display_type>
    <display_orientation>-</display_orientation>
    <sourcefile>src/devices/video/m50458.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>actfancr</name>
    <description>Act-Fancer Cybernetick Hyper Weapon (World revision 3)</description>
    <year>1989</year>
    <manufacturer>Data East Corporation</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>INCOMPLETO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>actfancr.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>afighter</name>
    <description>Action Fighter (FD1089A 317-0018)</description>
    <year>1986</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>VERTICAL</display_orientation>
    <sourcefile>segas16a.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>actionhw</name>
    <description>Action Hollywood</description>
    <year>1995</year>
    <manufacturer>TCH</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>INCOMPLETO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>kickgoal.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>aerofgt</name>
    <description>Aero Fighters (World / USA + Canada / Korea / Hong Kong / Taiwan) (newer hardware)</description>
    <year>1992</year>
    <manufacturer>Video System Co.</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>VERTICAL</display_orientation>
    <sourcefile>aerofgt.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>sonicwi2</name>
    <description>Aero Fighters 2 / Sonic Wings 2</description>
    <year>1994</year>
    <manufacturer>Video System Co.</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>neogeo.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>sonicwi3</name>
    <description>Aero Fighters 3 / Sonic Wings 3</description>
    <year>1995</year>
    <manufacturer>Video System Co.</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>neogeo.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>aerofgts</name>
    <description>Aero Fighters Special (Taiwan)</description>
    <year>1996</year>
    <manufacturer>Video System Co.</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>INCOMPLETO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>VERTICAL</display_orientation>
    <sourcefile>zn.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>coh1002v</name>
    <description>Video System PSX</description>
    <year>1996</year>
    <manufacturer>Video System Co.</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>INCOMPLETO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>zn.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>mt_aftrb</name>
    <description>After Burner (Mega-Tech, SMS based)</description>
    <year>1987</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>megatech.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>megatech</name>
    <description>Mega-Tech</description>
    <year>1989</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>megatech.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>aburner2</name>
    <description>After Burner II</description>
    <year>1987</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>segaxbd.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>aoh</name>
    <description>Age Of Heroes - Silkroad 2 (v0.63 - 2001/02/07)</description>
    <year>2001</year>
    <manufacturer>Unico</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>vamphalf.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>superbon</name>
    <description>Agent Super Bond (Super Cobra conversion)</description>
    <year>1985</year>
    <manufacturer>Signatron USA</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>VERTICAL</display_orientation>
    <sourcefile>galaxian.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>aodk</name>
    <description>Aggressors of Dark Kombat / Tsuukai GANGAN Koushinkyoku (ADM-008 ~ ADH-008)</description>
    <year>1994</year>
    <manufacturer>ADK / SNK</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>neogeo.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>agress</name>
    <description>Agress - Missile Daisenryaku (Japan)</description>
    <year>1991</year>
    <manufacturer>Palco</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>blockout.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>koshien</name>
    <description>Ah Eikou no Koshien (Japan)</description>
    <year>1990</year>
    <manufacturer>Taito Corporation</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>taito_f2.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>airass</name>
    <description>Air Assault (World)</description>
    <year>1993</year>
    <manufacturer>Irem</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>VERTICAL</display_orientation>
    <sourcefile>m107.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>airattck</name>
    <description>Air Attack (set 1)</description>
    <year>1996</year>
    <manufacturer>Comad</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>VERTICAL</display_orientation>
    <sourcefile>nmk16.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>airbustr</name>
    <description>Air Buster: Trouble Specialty Raid Unit (World)</description>
    <year>1990</year>
    <manufacturer>Kaneko (Namco license)</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>airbustr.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>aircomb</name>
    <description>Air Combat (AC2, US)</description>
    <year>1992</year>
    <manufacturer>Namco</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>namcos21_c67.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>namcoc68</name>
    <description>Namco C68 I/O</description>
    <year>-</year>
    <manufacturer>-</manufacturer>
    <is_runnable>NO</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>-</display_type>
    <display_orientation>-</display_orientation>
    <sourcefile>src/mame/machine/namco68.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>namcoc67</name>
    <description>Namco C67 (TMS320C25)</description>
    <year>-</year>
    <manufacturer>-</manufacturer>
    <is_runnable>NO</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>-</display_type>
    <display_orientation>-</display_orientation>
    <sourcefile>src/mame/machine/namco_c67.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>airco22b</name>
    <description>Air Combat 22 (Rev. ACS1 Ver.B, Japan)</description>
    <year>1995</year>
    <manufacturer>Namco</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>INCOMPLETO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>namcos22.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>airduel</name>
    <description>Air Duel (World, M82 hardware)</description>
    <year>1990</year>
    <manufacturer>Irem</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>VERTICAL</display_orientation>
    <sourcefile>m72.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>agallet</name>
    <description>Air Gallet (Europe)</description>
    <year>1996</year>
    <manufacturer>Gazelle (Banpresto license)</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>VERTICAL</display_orientation>
    <sourcefile>cave.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>ainferno</name>
    <description>Air Inferno (US)</description>
    <year>1990</year>
    <manufacturer>Taito America Corporation</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>taitoair.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>airrace</name>
    <description>Air Race (prototype)</description>
    <year>1985</year>
    <manufacturer>Atari Games</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>INCOMPLETO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>atarisy4.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>airraid</name>
    <description>Air Raid (Single PCB)</description>
    <year>1987</year>
    <manufacturer>Seibu Kaihatsu</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>VERTICAL</display_orientation>
    <sourcefile>airraid.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>arescue</name>
    <description>Air Rescue (World)</description>
    <year>1992</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>INCOMPLETO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>segas32.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>airtrix</name>
    <description>Air Trix (Rev A)</description>
    <year>2000</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>hikaru.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>hikaru</name>
    <description>Hikaru Bios</description>
    <year>2000</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>hikaru.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>airwlkrs</name>
    <description>Air Walkers</description>
    <year>1997</year>
    <manufacturer>Data East</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>model2.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>segabill</name>
    <description>Sega Billboard</description>
    <year>-</year>
    <manufacturer>-</manufacturer>
    <is_runnable>NO</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>-</display_type>
    <display_orientation>-</display_orientation>
    <sourcefile>src/mame/machine/segabill.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>alpilotj</name>
    <description>Airline Pilots (Japan, Rev A)</description>
    <year>1999</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>naomi.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>alpilot</name>
    <description>Airline Pilots (World, Rev B)</description>
    <year>1999</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>naomi.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>airlbios</name>
    <description>Naomi Airline Pilots (deluxe) Bios</description>
    <year>1999</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>naomi.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>airwolf</name>
    <description>Airwolf</description>
    <year>1987</year>
    <manufacturer>Kyugo</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>kyugo.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>ajax</name>
    <description>Ajax</description>
    <year>1987</year>
    <manufacturer>Konami</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>VERTICAL</display_orientation>
    <sourcefile>ajax.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>akatana</name>
    <description>Akai Katana (2010/ 8/13 MASTER VER.)</description>
    <year>2010</year>
    <manufacturer>Cave (AMI license)</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>INCOMPLETO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>cv1k.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>ausfache</name>
    <description>Akatsuki Blitzkampf Ausf. Achse (Japan)</description>
    <year>2008</year>
    <manufacturer>Subtle Style</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>naomi.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>akkaarrh</name>
    <description>Akka Arrh (prototype)</description>
    <year>1982</year>
    <manufacturer>Atari</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>akkaarrh.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>aladmdb</name>
    <description>Aladdin (bootleg of Japanese Megadrive version)</description>
    <year>1993</year>
    <manufacturer>bootleg / Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>megadriv_acbl.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>alcon</name>
    <description>Alcon (US)</description>
    <year>1986</year>
    <manufacturer>Toaplan / Taito America Corp.</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>VERTICAL</display_orientation>
    <sourcefile>slapfght.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>m68705p5</name>
    <description>Motorola MC68705P5</description>
    <year>-</year>
    <manufacturer>-</manufacturer>
    <is_runnable>NO</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>-</display_type>
    <display_orientation>-</display_orientation>
    <sourcefile>src/devices/cpu/m6805/m68705.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>alexkidd</name>
    <description>Alex Kidd: The Lost Stars (set 2, unprotected)</description>
    <year>1986</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>segas16a.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>alibaba</name>
    <description>Ali Baba and 40 Thieves</description>
    <year>1982</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>VERTICAL</display_orientation>
    <sourcefile>pacman.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>alienar</name>
    <description>Alien Arena</description>
    <year>1985</year>
    <manufacturer>Duncan Brown</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>williams.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>aliencha</name>
    <description>Alien Challenge (World)</description>
    <year>1994</year>
    <manufacturer>IGS</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>lordgun.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>aliencr</name>
    <description>Alien Crush (United Amusements PC Engine)</description>
    <year>1989</year>
    <manufacturer>Hudson Soft</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>INCOMPLETO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>uapce.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>alienfnt</name>
    <description>Alien Front (Rev T)</description>
    <year>2001</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>naomi.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>alinvade</name>
    <description>Alien Invaders</description>
    <year>198?</year>
    <manufacturer>Forbes?</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>VERTICAL</display_orientation>
    <sourcefile>alinvade.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>aliensec</name>
    <description>Alien Sector</description>
    <year>1985</year>
    <manufacturer>Namco</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>baraduke.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>mt_astrm</name>
    <description>Alien Storm (Mega-Tech)</description>
    <year>1990</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>megatech.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>astorm</name>
    <description>Alien Storm (World, 2 Players) (FD1094 317-0154)</description>
    <year>1990</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>segas18.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>mt_asyn</name>
    <description>Alien Syndrome (Mega-Tech, SMS based)</description>
    <year>1987</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>PRELIMINARE</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>megatech.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>aliensyn</name>
    <description>Alien Syndrome (set 4, System 16B, unprotected)</description>
    <year>1987</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>segas16b.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>avsp</name>
    <description>Alien vs. Predator (Euro 940520)</description>
    <year>1994</year>
    <manufacturer>Capcom</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>BUONO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>cps2.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>alien3</name>
    <description>Alien3: The Gun (World)</description>
    <year>1993</year>
    <manufacturer>Sega</manufacturer>
    <is_runnable>YES</is_runnable>
    <driver_status>INCOMPLETO</driver_status>
    <display_type>RASTER</display_type>
    <display_orientation>HORIZONTAL</display_orientation>
    <sourcefile>segas32.cpp</sourcefile>
  </arcade>
  <arcade>
    <name>aliens</name>